// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzFXbBq4RhUqkUo9IeBt0n2vKM0dPvJeo',
    appId: '1:805441065418:web:d79ecc90f60489955bbf33',
    messagingSenderId: '805441065418',
    projectId: 'chatapp-351e2',
    authDomain: 'chatapp-351e2.firebaseapp.com',
    databaseURL: 'https://chatapp-351e2-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-351e2.firebasestorage.app',
    measurementId: 'G-QQ8XXWGWSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLxZMCF7bXVA2M6LsE0kb3pF3B1Tdo9IM',
    appId: '1:805441065418:android:f6180675109490a15bbf33',
    messagingSenderId: '805441065418',
    projectId: 'chatapp-351e2',
    databaseURL: 'https://chatapp-351e2-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-351e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtSkNd34BqqDekeZ6mJfJ76nXIi6T7biw',
    appId: '1:805441065418:ios:44a7de5b12247bb35bbf33',
    messagingSenderId: '805441065418',
    projectId: 'chatapp-351e2',
    databaseURL: 'https://chatapp-351e2-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-351e2.firebasestorage.app',
    iosBundleId: 'me.naza.jandy.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtSkNd34BqqDekeZ6mJfJ76nXIi6T7biw',
    appId: '1:805441065418:ios:44a7de5b12247bb35bbf33',
    messagingSenderId: '805441065418',
    projectId: 'chatapp-351e2',
    databaseURL: 'https://chatapp-351e2-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-351e2.firebasestorage.app',
    iosBundleId: 'me.naza.jandy.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzFXbBq4RhUqkUo9IeBt0n2vKM0dPvJeo',
    appId: '1:805441065418:web:21c6ab56954f70885bbf33',
    messagingSenderId: '805441065418',
    projectId: 'chatapp-351e2',
    authDomain: 'chatapp-351e2.firebaseapp.com',
    databaseURL: 'https://chatapp-351e2-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-351e2.firebasestorage.app',
    measurementId: 'G-GCYW0CXJ06',
  );

}